### ISSUE TITLE
background_loop() missing 1 required positional argument

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#25]
Broken with commit 1672a42.

Bisect log:
```emerald@homepc:~/scubot$ git bisect good 03b091bff3d14a1f20a96f53355ae2acca8b1454
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[126801756bc70fc2811eeda34974e164f28e833b] cleaned up some code
emerald@homepc:~/scubot$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 1 step)
[90414bab3aae0883a3ca10a67b74b34cfcc4c0cd] make reddit post more compliant with module standards
emerald@homepc:~/scubot$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 1 step)
[1672a42aefef608bbd49a77b99e7d25ea5a46d94] Merge branch 'karma' into master
emerald@homepc:~/scubot$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[2a2ad4aa448a184480b0ed25801ed1b4f322f558] fix reaction listening
emerald@homepc:~/scubot$ git bisect good
1672a42aefef608bbd49a77b99e7d25ea5a46d94 is the first bad commit
emerald@homepc:~/scubot$ 
```
